name:  CoreLab CI (Lint & Tests)

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      # 1. On récupère le code du dépôt GitHub
      - name:  Checkout du code
        uses: actions/checkout@v4

      # 2. On installe l'environnement Node.js
      - name:  Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Server/package-lock.json

      - name:  Installation des dépendances
        run: |
          cd Server
          npm install

        # Étape de vérification de la syntaxe (Lint) et de compilation
      - name:  Vérification du code (Lint / Compilation)
        run: |
          cd Server
          npm run build --if-present

      #  On lance la suite de tests Jest qu'on a configurée 
      - name:  Exécution des tests d'intégration (Jest)
        env:
          JWT_SECRET: super_secret_key_ci_test_123
          PORT: 4242
        run: |
          cd Server
          npm test